const CHUNK_PUBLIC_PATH = "server/app/api/genkit/[...flow]/route.js";
const runtime = require("../../../../chunks/[turbopack]_runtime.js");
runtime.loadChunk("server/chunks/node_modules_node-fetch_src_index_fa1afa8a.js");
runtime.loadChunk("server/chunks/node_modules_next_5019e12a._.js");
runtime.loadChunk("server/chunks/node_modules_zod_lib_ae7c5ef1._.js");
runtime.loadChunk("server/chunks/node_modules_@genkit-ai_core_lib_1971a49a._.js");
runtime.loadChunk("server/chunks/node_modules_ajv_dist_4699a16a._.js");
runtime.loadChunk("server/chunks/node_modules_zod-to-json-schema_dist_e510fa2f._.js");
runtime.loadChunk("server/chunks/node_modules_@opentelemetry_793a8552._.js");
runtime.loadChunk("server/chunks/bf1d5_@opentelemetry_semantic-conventions_build_esm_41c4fa04._.js");
runtime.loadChunk("server/chunks/4292a_@opentelemetry_semantic-conventions_build_esm_ce953e68._.js");
runtime.loadChunk("server/chunks/node_modules_@opentelemetry_cb68fcf2._.js");
runtime.loadChunk("server/chunks/node_modules_@genkit-ai_ai_lib_b3cca82d._.js");
runtime.loadChunk("server/chunks/node_modules_handlebars_dist_cjs_4a6ba204._.js");
runtime.loadChunk("server/chunks/node_modules_yaml_dist_04fd9803._.js");
runtime.loadChunk("server/chunks/node_modules_@opentelemetry_resources_build_esm_53b99a33._.js");
runtime.loadChunk("server/chunks/node_modules_@opentelemetry_sdk-metrics_build_esm_36d82ede._.js");
runtime.loadChunk("server/chunks/node_modules_@opentelemetry_sdk-trace-base_build_esm_2004cd04._.js");
runtime.loadChunk("server/chunks/node_modules_protobufjs_d5aa50b8._.js");
runtime.loadChunk("server/chunks/node_modules_@opentelemetry_otlp-transformer_build_esm_8f2a63ec._.js");
runtime.loadChunk("server/chunks/node_modules_@grpc_grpc-js_d0c75999._.js");
runtime.loadChunk("server/chunks/node_modules_thriftrw_062273ac._.js");
runtime.loadChunk("server/chunks/node_modules_@opentelemetry_ff514040._.js");
runtime.loadChunk("server/chunks/node_modules_513f8d9b._.js");
runtime.loadChunk("server/chunks/[root-of-the-server]__12934d37._.js");
runtime.getOrInstantiateRuntimeModule("[project]/.next-internal/server/app/api/genkit/[...flow]/route/actions.js [app-rsc] (server actions loader, ecmascript)", CHUNK_PUBLIC_PATH);
runtime.getOrInstantiateRuntimeModule("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/genkit/[...flow]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)", CHUNK_PUBLIC_PATH);
module.exports = runtime.getOrInstantiateRuntimeModule("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/genkit/[...flow]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)", CHUNK_PUBLIC_PATH).exports;
